# run build scripts
# currently, this is:
#  RSS feed
#
# note:
#   if this makes changes, it will commit to the repository,
#   which will cancel the github pages action and re-run it
#   this sends a notification to me,
#   but I don't know an easier way to do this differently

name: Build scripts

on:
  push:
    branches:
      - main

jobs:
  scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make RSS Feed with Python
        run: |
          python ./utilities.py/rss_feed.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
