name: Create RSS feed

on:
  push:
    branches:
      - master
      - rss-feed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make RSS Feed (python)
        run: |
          python ./utilities.py/rss_feed.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: feed.xml
          path: ./feed.xml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
