# uses AI "embeddings" to create similar posts
# see https://tomhazledine.com/llm-related-posts/

name: Create similar posts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make suggestions
        run: |
          python ./utilities.py/embeddings.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
